name: balajiworkflow

on:
  workflow_dispatch:
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 'BalajiScript'
        run: |
          ls
          echo "testing the workflow "
          chmod +x ./.github/workflows/scripts/testscript.sh
          ./.github/workflows/scripts/testscript.sh
