name: balajiworkflow

on:
  workflow_dispatch:
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'BalajiScript'
        run: |
          echo "testing the workflow "
          chmod +x ./scripts/testscript.sh
          ./scripts/testscript.sh
