name: terraform-workflow-test

on:
  workflow_dispatch:
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Terraform API token
        run: |
            echo "Token: $TF_API_TOKEN"
            curl --location 'https://app.terraform.io/api/v2/organizations/MyFirstOrg-BalajiM/workspaces/MyFirstWorkspace' --header 'Authorization: Bearer ${{ secrets.SuperSecret }}'
      # - name: 'terraform api'
      #   run: |
      #     ls -a
      #     echo "testing the workflow "
      #     chmod +x ./.github/workflows/scripts/terraform-api.sh
      #     ./.github/workflows/scripts/terraform-api.sh
