name: terraform-workflow-test

on:
  workflow_dispatch:
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: fetch workspace id
        run: |
            workspaceId=$(curl --location 'https://app.terraform.io/api/v2/organizations/MyFirstOrg-BalajiM/workspaces/MyFirstWorkspace' --header 'Authorization: Bearer ${{ secrets.TF_API_TOKEN }}')
            echo "$workspaceId"
      - name: 'terraform api'
        run: |
          ls -a
          echo "testing the workflow "
          chmod +x ./.github/workflows/scripts/terraform-api.sh
          ./.github/workflows/scripts/terraform-api.sh ${{ secrets.TF_API_TOKEN }}
