name: terraform-cli

on:
  workflow_dispatch:
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: terraform cli
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Checkout code
        uses: actions/checkout@v2

      - name: list files
        run: |
           ls -a       
           
      - name: terraform initialization
        id: init
        run: |
          cd tf
          ls
          terraform init
          
      - name: terraform plan 
        id: plan
        run: |
          terraform plan
        
      - name: Terraform Validate
        id: validate
        run: |
          terraform validate
       
